Test error in Ruby => C ext support => Ruby
/test/truffle/cexts/backtraces/bin/backtraces:16:in `callback': Ruby callback error (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `__send__'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcallv'
	from /src/main/c/cext/ruby.c:1994:in `rb_funcallv'
	from /test/truffle/cexts/backtraces/bin/backtraces:20:in `ruby_call'
	from /test/truffle/cexts/backtraces/bin/backtraces:24:in `top'
	from /test/truffle/cexts/backtraces/bin/backtraces:28:in `<main>'

Test with an internal error from rb_mutex_lock()
/lib/truffle/truffle/cext.rb:n:in `lock': deadlock; recursive locking (ThreadError)
	from /lib/truffle/truffle/cext.rb:n:in `rb_mutex_lock'
	from /src/main/c/cext/ruby.c:2593:in `rb_mutex_lock'
	from /test/truffle/cexts/backtraces/bin/backtraces:42:in `double_lock'
	from /test/truffle/cexts/backtraces/bin/backtraces:46:in `<main>'

Test error in Ruby => C ext => Ruby => C ext Proc => Ruby
/test/truffle/cexts/backtraces/bin/backtraces:56:in `block in bar': error (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `call'
	from /lib/truffle/truffle/cext.rb:n:in `__send__'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:5:in `baz'
	from /lib/truffle/truffle/cext.rb:n:in `execute_without_conversion'
	from /lib/truffle/truffle/cext.rb:n:in `execute_with_mutex'
	from /lib/truffle/truffle/cext.rb:n:in `block in rb_proc_new'
	from /test/truffle/cexts/backtraces/bin/backtraces:56:in `call'
	from /test/truffle/cexts/backtraces/bin/backtraces:56:in `bar'
	from /lib/truffle/truffle/cext.rb:n:in `__send__'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:9:in `foo'
	from /lib/truffle/truffle/cext.rb:n:in `execute_without_conversion'
	from /lib/truffle/truffle/cext.rb:n:in `execute_with_mutex'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `foo'
	from /test/truffle/cexts/backtraces/bin/backtraces:61:in `<main>'

Test error in the callback to the Sulong-instrinsified qsort()
[1, 2, 3, 4]
/test/truffle/cexts/backtraces/bin/backtraces:73:in `lambda': error from Ruby called from instrinsified qsort() (RuntimeError)
	from /lib/truffle/truffle/cext.rb:n:in `call'
	from /lib/truffle/truffle/cext.rb:n:in `__send__'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:17:in `compare_function'
	from libsulong.bc:@sulong_qsort:1:in `sulong_qsort'
	from libsulong.bc:@qsort:1:in `qsort'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:25:in `call_qsort'
	from /lib/truffle/truffle/cext.rb:n:in `execute_without_conversion'
	from /lib/truffle/truffle/cext.rb:n:in `execute_with_mutex'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `qsort'
	from /test/truffle/cexts/backtraces/bin/backtraces:72:in `<main>'

Test error in callback from a native function
42
/lib/truffle/truffle/cext.rb:n:in `execute_without_conversion': Error in C extension code (SulongRuntimeException):
Exception thrown by a callback during the native call com.oracle.truffle.nfi.impl.LibFFIFunction@HEXA(function@HEXA '@sulong_callback') (IllegalStateException)
	from native_callback in backtraces.c:43:17 (LLVM IR Function native_callback in /test/truffle/cexts/backtraces/lib/backtraces/backtraces.su@HEXA_backtraces.bc in Block BLOCKINFO)
	from com.oracle.truffle.llvm.nodes.func.LLVMNativeCallUtils.callNativeFunction(LLVMNativeCallUtils.java:72)
Caused by:
/test/truffle/cexts/backtraces/bin/backtraces:85:in `error_helper': error from Ruby called from Sulong called from native callback (RuntimeError)
	from /test/truffle/cexts/backtraces/bin/backtraces:90:in `lambda'
	from /lib/truffle/truffle/cext.rb:n:in `call'
	from /lib/truffle/truffle/cext.rb:n:in `__send__'
	from /lib/truffle/truffle/cext.rb:n:in `rb_funcall'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:38:in `sulong_callback'
	from /test/truffle/cexts/backtraces/ext/backtraces/backtraces.c:44:in `native_callback'
	from /lib/truffle/truffle/cext.rb:n:in `execute_without_conversion'
	from /lib/truffle/truffle/cext.rb:n:in `execute_with_mutex'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `native_callback'
	from /test/truffle/cexts/backtraces/bin/backtraces:89:in `<main>'
Translated to internal error (RubyTruffleError)
	from /lib/truffle/truffle/cext.rb:n:in `execute_with_mutex'
	from /lib/truffle/truffle/cext_ruby.rb:n:in `native_callback'
	from /test/truffle/cexts/backtraces/bin/backtraces:89:in `<main>'
